### ISSUE TITLE
UIWebView deprecation

### ISSUE THREAD

**Issue by jlews** [Plotprojects/plot-phonegap-plugin#15]
As of April 2020, Apple are no longer accepting new app submissions that use the deprecated `UIWebView` component from Apple's `UIKit`.

Currently, adding the latest version of this cordova plugin to an otherwise compliant project results in the build being rejected by Apple with the following explanation:

**ITMS-90809: Deprecated API Usage** - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Here's some more detail from Apple on the deprecation:
https://developer.apple.com/news/?id=12232019b

**Comment by marshall20** [comment]
Thanks for your comment. We're going to release a new version soon with the WkWebView

**Comment by marshall20** [comment]
This is issue is solved on the latest release
