### ISSUE TITLE
ios app not requesting to use location

### ISSUE THREAD

**Issue by etrey** [Plotprojects/plot-phonegap-plugin#5]
I am assuming that this will not work unless the user allows to share their location via first-time launch or privacy settings?

**Comment by markvandertol** [comment]
When you integrate Plot as explained on [our project page](https://github.com/Plotprojects/plot-phonegap-plugin) then the Plot plugin asks for the location opt-in. For Plot to work correctly the user indeed has to opt-in then, or later by allowing location services for this app in the settings.

Does this answer your question?
