### ISSUE TITLE
duplicate issue with libPlot-v1_11_1.a

### ISSUE THREAD

**Issue by thienchau** [Plotprojects/plot-phonegap-plugin#7]
Hi,
I'm integrating libPlot-v1_11_1.a and got many issue about duplicate
- xcode 6.4
- swift 1

duplicate symbol _llvm.cmdline in:
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(Plot.o)
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(PlotPPlotInterface.o)
duplicate symbol _llvm.embedded.module in:
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(Plot.o)
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(PlotPPlotInterface.o)
..........
duplicate symbol _llvm.cmdline in:
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(Plot.o)
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(PlotPCooldownGroup.o)
duplicate symbol _llvm.embedded.module in:
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(Plot.o)
    /Users/imac02/Documents/Projects/liive/Liive/libPlot-v1_11_1.a(PlotPCooldownGroup.o)
ld: 140 duplicate symbols for architecture x86_64

Anyone can help me this?

**Comment by markvandertol** [comment]
This repository is only for the Phonegap support of the Plot Plugin. 

Also, please ask your support questions at a single place. I've answered your question here: https://groups.google.com/forum/#!topic/plot-users/K9lLAPNJlH4
