### ISSUE TITLE
Documentation should include plot.init and other "Getting Started" examples.

### ISSUE THREAD

**Issue by adam-back** [Plotprojects/plot-phonegap-plugin#8]
The [Phonegap integration website](http://www.plotprojects.com/phonegap-integration/) does an ok step-by-step of how to use the plugin, but it's not quite a "Hello World" example. It makes use of the `plot.init` function, but doesn't say why it's used and it's not documented in this README.

I think it would be most helpful to a new user, testing out Plot for the first time, if the README were ordered as a step-by-step, instead of having to navigate to an outside page. I'm happy to submit a draft these changes as a PR if requested.

I'm also happy to contribute an Ionic (Angular on top of Cordova) example.

**Comment by markvandertol** [comment]
All the integration guides are currently on our website, which is for the time being not something we would like to change. We could improve on this by letting the link to the integration guide stand out more.

**Comment by markvandertol** [comment]
We will extend the documentation in the near future to better explain how to get started and what properties can be passed to plot.init. Also we'll add a section about Ionic.

Other parts of the method reference are already expanded to explain more about the callbacks.

**Comment by markvandertol** [comment]
A better integration guide has been added under **Integration Guide** that shows how to get started. Also the plot.init method is now documented.
